/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedVacinasRouteImport } from './routes/_authenticated.vacinas'
import { Route as AuthenticatedVacinacaoRouteImport } from './routes/_authenticated.vacinacao'
import { Route as AuthenticatedVacasRouteImport } from './routes/_authenticated.vacas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated.producao'
import { Route as AuthenticatedMinhaContaRouteImport } from './routes/_authenticated.minha-conta'
import { Route as AuthenticatedAuditoriaRouteImport } from './routes/_authenticated.auditoria'
import { Route as AuthenticatedVacasIndexRouteImport } from './routes/_authenticated.vacas.index'
import { Route as AuthenticatedVacasIdRouteImport } from './routes/_authenticated.vacas.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVacinasRoute = AuthenticatedVacinasRouteImport.update({
  id: '/vacinas',
  path: '/vacinas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVacinacaoRoute = AuthenticatedVacinacaoRouteImport.update({
  id: '/vacinacao',
  path: '/vacinacao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVacasRoute = AuthenticatedVacasRouteImport.update({
  id: '/vacas',
  path: '/vacas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/producao',
  path: '/producao',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMinhaContaRoute = AuthenticatedMinhaContaRouteImport.update({
  id: '/minha-conta',
  path: '/minha-conta',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditoriaRoute = AuthenticatedAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVacasIndexRoute = AuthenticatedVacasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedVacasRoute,
} as any)
const AuthenticatedVacasIdRoute = AuthenticatedVacasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVacasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vacas': typeof AuthenticatedVacasRouteWithChildren
  '/vacinacao': typeof AuthenticatedVacinacaoRoute
  '/vacinas': typeof AuthenticatedVacinasRoute
  '/vacas/$id': typeof AuthenticatedVacasIdRoute
  '/vacas/': typeof AuthenticatedVacasIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/auditoria': typeof AuthenticatedAuditoriaRoute
  '/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vacinacao': typeof AuthenticatedVacinacaoRoute
  '/vacinas': typeof AuthenticatedVacinasRoute
  '/': typeof AuthenticatedIndexRoute
  '/vacas/$id': typeof AuthenticatedVacasIdRoute
  '/vacas': typeof AuthenticatedVacasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/auditoria': typeof AuthenticatedAuditoriaRoute
  '/_authenticated/minha-conta': typeof AuthenticatedMinhaContaRoute
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vacas': typeof AuthenticatedVacasRouteWithChildren
  '/_authenticated/vacinacao': typeof AuthenticatedVacinacaoRoute
  '/_authenticated/vacinas': typeof AuthenticatedVacinasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vacas/$id': typeof AuthenticatedVacasIdRoute
  '/_authenticated/vacas/': typeof AuthenticatedVacasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/auditoria'
    | '/minha-conta'
    | '/producao'
    | '/relatorios'
    | '/vacas'
    | '/vacinacao'
    | '/vacinas'
    | '/vacas/$id'
    | '/vacas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/auditoria'
    | '/minha-conta'
    | '/producao'
    | '/relatorios'
    | '/vacinacao'
    | '/vacinas'
    | '/'
    | '/vacas/$id'
    | '/vacas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/auditoria'
    | '/_authenticated/minha-conta'
    | '/_authenticated/producao'
    | '/_authenticated/relatorios'
    | '/_authenticated/vacas'
    | '/_authenticated/vacinacao'
    | '/_authenticated/vacinas'
    | '/_authenticated/'
    | '/_authenticated/vacas/$id'
    | '/_authenticated/vacas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacinas': {
      id: '/_authenticated/vacinas'
      path: '/vacinas'
      fullPath: '/vacinas'
      preLoaderRoute: typeof AuthenticatedVacinasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacinacao': {
      id: '/_authenticated/vacinacao'
      path: '/vacinacao'
      fullPath: '/vacinacao'
      preLoaderRoute: typeof AuthenticatedVacinacaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacas': {
      id: '/_authenticated/vacas'
      path: '/vacas'
      fullPath: '/vacas'
      preLoaderRoute: typeof AuthenticatedVacasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-conta': {
      id: '/_authenticated/minha-conta'
      path: '/minha-conta'
      fullPath: '/minha-conta'
      preLoaderRoute: typeof AuthenticatedMinhaContaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/auditoria': {
      id: '/_authenticated/auditoria'
      path: '/auditoria'
      fullPath: '/auditoria'
      preLoaderRoute: typeof AuthenticatedAuditoriaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vacas/': {
      id: '/_authenticated/vacas/'
      path: '/'
      fullPath: '/vacas/'
      preLoaderRoute: typeof AuthenticatedVacasIndexRouteImport
      parentRoute: typeof AuthenticatedVacasRoute
    }
    '/_authenticated/vacas/$id': {
      id: '/_authenticated/vacas/$id'
      path: '/$id'
      fullPath: '/vacas/$id'
      preLoaderRoute: typeof AuthenticatedVacasIdRouteImport
      parentRoute: typeof AuthenticatedVacasRoute
    }
  }
}

interface AuthenticatedVacasRouteChildren {
  AuthenticatedVacasIdRoute: typeof AuthenticatedVacasIdRoute
  AuthenticatedVacasIndexRoute: typeof AuthenticatedVacasIndexRoute
}

const AuthenticatedVacasRouteChildren: AuthenticatedVacasRouteChildren = {
  AuthenticatedVacasIdRoute: AuthenticatedVacasIdRoute,
  AuthenticatedVacasIndexRoute: AuthenticatedVacasIndexRoute,
}

const AuthenticatedVacasRouteWithChildren =
  AuthenticatedVacasRoute._addFileChildren(AuthenticatedVacasRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAuditoriaRoute: typeof AuthenticatedAuditoriaRoute
  AuthenticatedMinhaContaRoute: typeof AuthenticatedMinhaContaRoute
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVacasRoute: typeof AuthenticatedVacasRouteWithChildren
  AuthenticatedVacinacaoRoute: typeof AuthenticatedVacinacaoRoute
  AuthenticatedVacinasRoute: typeof AuthenticatedVacinasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAuditoriaRoute: AuthenticatedAuditoriaRoute,
  AuthenticatedMinhaContaRoute: AuthenticatedMinhaContaRoute,
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVacasRoute: AuthenticatedVacasRouteWithChildren,
  AuthenticatedVacinacaoRoute: AuthenticatedVacinacaoRoute,
  AuthenticatedVacinasRoute: AuthenticatedVacinasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
