/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedVacinasRouteImport } from './routes/_authenticated.vacinas'
import { Route as AuthenticatedVacinacaoRouteImport } from './routes/_authenticated.vacinacao'
import { Route as AuthenticatedVacasRouteImport } from './routes/_authenticated.vacas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated.relatorios'
import { Route as AuthenticatedProducaoRouteImport } from './routes/_authenticated.producao'
import { Route as AuthenticatedVacasIndexRouteImport } from './routes/_authenticated.vacas.index'
import { Route as AuthenticatedVacasIdRouteImport } from './routes/_authenticated.vacas.$id'

const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/_authenticated/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVacinasRoute = AuthenticatedVacinasRouteImport.update({
  id: '/_authenticated/vacinas',
  path: '/vacinas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVacinacaoRoute = AuthenticatedVacinacaoRouteImport.update({
  id: '/_authenticated/vacinacao',
  path: '/vacinacao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVacasRoute = AuthenticatedVacasRouteImport.update({
  id: '/_authenticated/vacas',
  path: '/vacas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/_authenticated/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProducaoRoute = AuthenticatedProducaoRouteImport.update({
  id: '/_authenticated/producao',
  path: '/producao',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVacasIndexRoute = AuthenticatedVacasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedVacasRoute,
} as any)
const AuthenticatedVacasIdRoute = AuthenticatedVacasIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedVacasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vacas': typeof AuthenticatedVacasRouteWithChildren
  '/vacinacao': typeof AuthenticatedVacinacaoRoute
  '/vacinas': typeof AuthenticatedVacinasRoute
  '/': typeof AuthenticatedIndexRoute
  '/vacas/$id': typeof AuthenticatedVacasIdRoute
  '/vacas/': typeof AuthenticatedVacasIndexRoute
}
export interface FileRoutesByTo {
  '/producao': typeof AuthenticatedProducaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/vacinacao': typeof AuthenticatedVacinacaoRoute
  '/vacinas': typeof AuthenticatedVacinasRoute
  '/': typeof AuthenticatedIndexRoute
  '/vacas/$id': typeof AuthenticatedVacasIdRoute
  '/vacas': typeof AuthenticatedVacasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/producao': typeof AuthenticatedProducaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/vacas': typeof AuthenticatedVacasRouteWithChildren
  '/_authenticated/vacinacao': typeof AuthenticatedVacinacaoRoute
  '/_authenticated/vacinas': typeof AuthenticatedVacinasRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/vacas/$id': typeof AuthenticatedVacasIdRoute
  '/_authenticated/vacas/': typeof AuthenticatedVacasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/producao'
    | '/relatorios'
    | '/vacas'
    | '/vacinacao'
    | '/vacinas'
    | '/'
    | '/vacas/$id'
    | '/vacas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/producao'
    | '/relatorios'
    | '/vacinacao'
    | '/vacinas'
    | '/'
    | '/vacas/$id'
    | '/vacas'
  id:
    | '__root__'
    | '/_authenticated/producao'
    | '/_authenticated/relatorios'
    | '/_authenticated/vacas'
    | '/_authenticated/vacinacao'
    | '/_authenticated/vacinas'
    | '/_authenticated/'
    | '/_authenticated/vacas/$id'
    | '/_authenticated/vacas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedProducaoRoute: typeof AuthenticatedProducaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedVacasRoute: typeof AuthenticatedVacasRouteWithChildren
  AuthenticatedVacinacaoRoute: typeof AuthenticatedVacinacaoRoute
  AuthenticatedVacinasRoute: typeof AuthenticatedVacinasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vacinas': {
      id: '/_authenticated/vacinas'
      path: '/vacinas'
      fullPath: '/vacinas'
      preLoaderRoute: typeof AuthenticatedVacinasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vacinacao': {
      id: '/_authenticated/vacinacao'
      path: '/vacinacao'
      fullPath: '/vacinacao'
      preLoaderRoute: typeof AuthenticatedVacinacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vacas': {
      id: '/_authenticated/vacas'
      path: '/vacas'
      fullPath: '/vacas'
      preLoaderRoute: typeof AuthenticatedVacasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/producao': {
      id: '/_authenticated/producao'
      path: '/producao'
      fullPath: '/producao'
      preLoaderRoute: typeof AuthenticatedProducaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vacas/': {
      id: '/_authenticated/vacas/'
      path: '/'
      fullPath: '/vacas/'
      preLoaderRoute: typeof AuthenticatedVacasIndexRouteImport
      parentRoute: typeof AuthenticatedVacasRoute
    }
    '/_authenticated/vacas/$id': {
      id: '/_authenticated/vacas/$id'
      path: '/$id'
      fullPath: '/vacas/$id'
      preLoaderRoute: typeof AuthenticatedVacasIdRouteImport
      parentRoute: typeof AuthenticatedVacasRoute
    }
  }
}

interface AuthenticatedVacasRouteChildren {
  AuthenticatedVacasIdRoute: typeof AuthenticatedVacasIdRoute
  AuthenticatedVacasIndexRoute: typeof AuthenticatedVacasIndexRoute
}

const AuthenticatedVacasRouteChildren: AuthenticatedVacasRouteChildren = {
  AuthenticatedVacasIdRoute: AuthenticatedVacasIdRoute,
  AuthenticatedVacasIndexRoute: AuthenticatedVacasIndexRoute,
}

const AuthenticatedVacasRouteWithChildren =
  AuthenticatedVacasRoute._addFileChildren(AuthenticatedVacasRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedProducaoRoute: AuthenticatedProducaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedVacasRoute: AuthenticatedVacasRouteWithChildren,
  AuthenticatedVacinacaoRoute: AuthenticatedVacinacaoRoute,
  AuthenticatedVacinasRoute: AuthenticatedVacinasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
